server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: foundation-swagger
          uri: lb://foundation-service
          predicates:
            - Path=/swagger/foundation/**
          filters:
            - RewritePath=/swagger/foundation/(?<segment>.*), /${segment}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
