spring:
  application:
    name: api-gateway

  spring:
  cloud:
    gateway:
      routes:
        - id: foundation-service
          uri: lb://foundation-service
          predicates:
            - Path=/foundation-service/**
          filters:
            - RewritePath=/foundation-service/(?<segment>.*), /${segment}
        
        - id: animal-service
          uri: lb://animal-service
          predicates:
            - Path=/animal-service/**
          filters:
            - RewritePath=/animal-service/(?<segment>.*), /${segment}

       
        
        - id: foundation-swagger
          uri: lb://foundation-service
          predicates:
            - Path=/swagger/foundation/**
          filters:
            - RewritePath=/swagger/foundation/(?<segment>.*), /${segment}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
