server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: foundation-service
          uri: lb://foundation-service
          predicates:
            - Path=/foundation-service/**
          filters:
            - RewritePath=/foundation-service/(?<segment>.*), /${segment}
            - RewriteResponseHeader=Location, /(?<path>.*), /foundation-service/${path}
    discovery:
      locator:
        enabled: true
        lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true
