server:
  port: 0
  servlet:
    context-path: /foundation-service

spring:
  application:
    name: foundation-service

  datasource:
    url: jdbc:postgresql://foundation-db:5432/foundationdb
    username: foundationUser
    password: foundation123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
